spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1037192318729-k33o0tesvo03fcv1vpuhh4vlkkhtctfc.apps.googleusercontent.com
            client-secret: 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
          github:
            client-id: Ov23liLacwfks9KXNqsy
            client-secret: b68e0ce3c86633d4523dfc38b7b2f9c272500a3e
